name: 🐛 Bug Report
description: Report a bug or unexpected behavior in Multi-Timer Audio Recorder
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out this form to help us understand and reproduce the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-flight Checklist
      description: Please confirm you have completed these steps
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I have reproduced this issue with the latest version
          required: true
        - label: I have checked the browser console for any error messages
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to...
        2. Click on...
        3. Set timer to...
        4. Start recording...
        5. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened instead
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of the app is affected?
      options:
        - Stopwatch
        - Timer
        - Audio Recorder
        - Waveform Visualizer
        - Unified Controls (Start/Pause/Reset All)
        - Local Storage/Session Persistence
        - UI/Layout
        - Other
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: What version of the browser? (e.g., 120.0.6099.109)
      placeholder: "120.0.6099.109"

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
        - iOS
        - Android
        - Other
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: What version of the operating system?
      placeholder: "Windows 11, macOS 14.2, Ubuntu 22.04, etc."

  - type: dropdown
    id: device
    attributes:
      label: Device Type
      description: What type of device are you using?
      options:
        - Desktop/Laptop
        - Mobile Phone
        - Tablet
        - Other

  - type: textarea
    id: console-errors
    attributes:
      label: Console Errors
      description: Any error messages from the browser console?
      placeholder: |
        Paste any error messages from the browser developer console here.
        Press F12 > Console tab to see errors.
      render: text

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem
      placeholder: Drag and drop screenshots here or paste image URLs

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Any other context about the problem?
        - Audio file formats being used
        - Specific timer durations
        - Recording length
        - Browser permissions for microphone
      placeholder: Add any other context or information that might be helpful

  - type: checkboxes
    id: terms
    attributes:
      label: Agreement
      description: By submitting this issue, you agree to follow our [Code of Conduct](../../blob/main/CONTRIBUTING.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true