blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/yuis-ice/multi-timer-audio-recorder/discussions
    about: General questions, feature discussions, and community conversations
  
  - name: 📖 Documentation
    url: https://github.com/yuis-ice/multi-timer-audio-recorder#readme
    about: Check the README for usage instructions and setup guide
  
  - name: 🔧 Troubleshooting
    url: https://github.com/yuis-ice/multi-timer-audio-recorder/discussions/categories/q-a
    about: Get help with setup, configuration, and common issues